version: '3.4'

services:
#Adding mongo to container

  catalogdb:
    image: mongo

    #Add redis to container

  basketdb:
    image: redis:alpine

    #Add postgreSQL to container

  discountdb:
    image: postgres

#Add Sql server to container
  orderdb:
    image: mcr.microsoft.com/mssql/server

#adding RabbitMQ Image to project from dockerhub.
  rabbitmq:
    image: rabbitmq:3-management-alpine

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

#configure to store data on docker volume
  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

volumes: 
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:
     





